{% set name = "huggingface_hub" %}
{% set version = "0.0.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/huggingface/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 72621edcc2d6c2ca62a70c12f28a89345fc44b9dc7bc175a5ae3a6e7c6d6ad24

build:
  number: 1
  noarch: python
  entry_points:
    - huggingface-cli=huggingface_hub.commands.huggingface_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip {{ pip }}
    - python
  run:
    - filelock
    - python
    - packaging
    - requests {{ requests }}
    - tqdm  {{ tqdm }}
    - typing-extensions  {{ typing_extensions }}
    - pyyaml {{ pyyaml }}
    # Only required for [py<38] but always include so this can be noarch: python
    - importlib_metadata

test:
  imports:
    - huggingface_hub
    - huggingface_hub.commands
  commands:
    - pip check
    - huggingface-cli --help
  requires:
    - git
    - git-lfs
    - pip

about:
  home: https://github.com/huggingface/huggingface_hub
  summary: Client library to download and publish models on the huggingface.co hub
  description: Client library to download and publish models on the huggingface.co hub
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
